trigger:
- main
- develop

pool:
  vmImage: ubuntu-latest

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '18.x'
  displayName: 'install node.js'

- script: |
    yarn install
    yarn build
  displayName: 'yarn install and build'

- script: yarn lint-run
  displayName: 'eslint code analysis'

- script: yarn test
  displayName: 'run unit tests using jest'



